name: Build Tailwind and Commit

on:
  push:
    branches:
      - main

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # important to use your token

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Tailwind CSS
        run: npm run build:css

      - name: Commit built CSS
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add static/css/output.css
          git commit -m "ci: build tailwind"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
